export enum DocumentStatus {
  PENDING = 'PENDING',
  UPLOADED = 'UPLOADED',
  REVIEW_PENDING = 'REVIEW_PENDING',
  PENDING_WITH_CLIENT = 'PENDING_WITH_CLIENT',
  PENDING_WITH_ADMIN = 'PENDING_WITH_ADMIN',
  APPROVED = 'APPROVED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}
